# Generated by Django 5.1.7 on 2025-03-18 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_alter_post_options_alter_topic_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentary",
            options={"ordering": ["created_at"], "verbose_name": "Commentarys"},
        ),
        migrations.AlterModelOptions(
            name="followers",
            options={"verbose_name": "Followers"},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at", "topic"], "verbose_name": "Posts"},
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ["name"], "verbose_name": "Topics"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["username"], "verbose_name": "Users"},
        ),
    ]
