# Generated by Django 5.1.7 on 2025-03-19 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_alter_commentary_options_alter_followers_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field", models.CharField(max_length=55, unique=True)),
            ],
            options={
                "verbose_name": "Field",
                "ordering": ["field"],
            },
        ),
        migrations.AlterModelOptions(
            name="commentary",
            options={"ordering": ["created_at"], "verbose_name": "Commentarie"},
        ),
        migrations.AlterModelOptions(
            name="followers",
            options={"verbose_name": "Follower"},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at", "topic"], "verbose_name": "Post"},
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ["name"], "verbose_name": "Topic"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["username"], "verbose_name": "User"},
        ),
        migrations.RemoveField(
            model_name="post",
            name="comments",
        ),
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.ForeignKey(
                max_length=55,
                on_delete=django.db.models.deletion.CASCADE,
                to="post.field",
                unique=True,
            ),
        ),
    ]
