# Generated by Django 5.1.7 on 2025-03-19 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_field_alter_commentary_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.OneToOneField(
                max_length=55,
                on_delete=django.db.models.deletion.CASCADE,
                to="post.field",
            ),
        ),
    ]
