# Generated by Django 5.1.7 on 2025-03-19 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0006_alter_topic_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="field",
            options={"ordering": ["name"], "verbose_name": "Field"},
        ),
        migrations.RenameField(
            model_name="field",
            old_name="field",
            new_name="name",
        ),
    ]
