# Generated by Django 5.1.7 on 2025-03-19 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0007_alter_field_options_rename_field_field_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="field",
            field=models.OneToOneField(
                default=None,
                max_length=55,
                on_delete=django.db.models.deletion.CASCADE,
                to="post.field",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.CharField(max_length=55, unique=True),
        ),
    ]
