# Generated by Django 5.1.7 on 2025-04-02 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0009_alter_topic_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="topic",
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"], "verbose_name": "Post"},
        ),
        migrations.AddField(
            model_name="post",
            name="subtext",
            field=models.TextField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name="commentary",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commentary",
                to="post.post",
            ),
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=55, unique=True)),
                (
                    "field",
                    models.ForeignKey(
                        default=None,
                        max_length=55,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="post.field",
                    ),
                ),
            ],
            options={
                "verbose_name": "Section",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="post",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="post.section",
            ),
        ),
        migrations.DeleteModel(
            name="Topic",
        ),
    ]
