# Generated by Django 5.1.7 on 2025-03-19 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0009_alter_topic_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="field",
            field=models.ForeignKey(
                default=None,
                max_length=55,
                on_delete=django.db.models.deletion.CASCADE,
                to="post.field",
            ),
        ),
    ]
