# Generated by Django 5.1.4 on 2025-04-03 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0010_remove_post_topic_alter_post_options_post_subtext_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="subtext",
            new_name="title",
        ),
    ]
