# Generated by Django 5.1.7 on 2025-03-24 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0010_alter_topic_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="field",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="post.topic",
            ),
        ),
        migrations.AlterField(
            model_name="commentary",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commentary",
                to="post.post",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="topic",
            field=models.TextField(blank=True, max_length=55),
        ),
    ]
