# Generated by Django 5.1.7 on 2025-04-02 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0011_post_field_alter_commentary_post_alter_post_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="field",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="post.field",
            ),
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at", "name"], "verbose_name": "Post"},
        ),
        migrations.RemoveField(
            model_name="post",
            name="topic",
        ),
        migrations.AddField(
            model_name="post",
            name="name",
            field=models.TextField(blank=True, max_length=55),
        ),
        migrations.DeleteModel(
            name="Topic",
        ),
    ]
