# Generated by Django 5.1.4 on 2025-04-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0011_rename_subtext_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.TextField(blank=True),
        ),
    ]
