# Generated by Django 5.1.7 on 2025-04-02 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0012_alter_post_field_alter_post_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"], "verbose_name": "Post"},
        ),
        migrations.RenameField(
            model_name="post",
            old_name="name",
            new_name="subtext",
        ),
    ]
